POST http://localhost:1111/product/create HTTP/1.1
content-type: application/json

{
    "name": "gmail",
    "price": "42342dwdw"
}

###

GET http://localhost:1111/product/getAll HTTP/1.1
content-type: application/json

{}

###
GET http://localhost:1111/product/getProductByName HTTP/1.1
content-type: application/json

{
    "name": "Rok",
    "price": 20000
}

###

DELETE http://localhost:1111/product/deleteProductByID HTTP/1.1
content-type: application/json

{
    "id": 1
}